### ISSUE TITLE
All Procedures Crash with More than one argument

### ISSUE THREAD

**Issue by ghost** [nmilkosky/PrologFinal#2]
If a class has two methods, it crashes with an out of local stack error.
If a method contains more than one statement, it crashes with the same error.

Tried working on it for a couple hours. Cannot fix, need team to jump in, maybe another set of eyes will shed some light on the issue.

**Comment by huanga9** [comment]
Sure. Can you post an example of a test case that you are using?

**Comment by ghost** [comment]
Test Case 1: Two methods
parse([public,class,test,'{',public,test,'(',')','{','}',public,static,void,main,'(',')','{','}','}']).

Test Case 2: Two variables
parse([public,class,test,'{',public,test,'(',')','{',int,x,=,3,';',int,y,=,0,';','}','}']).

**Comment by nmilkosky** [comment]
Pretty sure it's fixed now, most test cases seem to work that I can think of.
